zuihou:
  mysql:
    database: zuihou_demo_dev       # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: root

logging:
  io.seata: debug
  org.springframework.cloud.alibaba.seata.web: debug

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${zuihou.mysql.host}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull

