zuihou:
  ip:
    nginx: 127.0.0.1
  port:
    nginx: 10000
  mysql:
    database: zuihou_file_dev
  file:
    type: LOCAL # FAST_DFS LOCAL
    storage-path: /projects/uploadfile/file/  # window 改成  D:\\projects\\uploadfile\\file\\

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://${zuihou.mysql.host}:${zuihou.mysql.port}/${zuihou.mysql.database}?serverTimezone=CTT&characterEncoding=utf8&useUnicode=true&useSSL=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull
